name: Update Readme.md with chess.com ascii graph
on:
  push:
    branches: master
  schedule:
    - cron: "0 */5 * * *"
jobs:
  ratings-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GH_TOKEN }}
        name: Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
        name: Install dependencies
      - run: pip install -r requirements.txt
        name: Create Chart
      - run: |
          python rating_chart.py > chart.txt
          CHART=$(cat chart.txt)
          echo "::set-output name=chart::$CHART"
      - run: cat README-1.md > README.md
      - run: cat chart.txt >> README.md
      - run: |
          currentDate=`env TZ=Asia/Kolkata date`
          printf "\nChart last updated - ${currentDate}" >> README.md
      - run: cat README-2.md >> README.md
        name: Update workflow yaml file
      - run: |
          python generate_random_workflow.py > rating-yaml.txt
          YAML=$(cat rating-yaml.txt)
          echo "::set-output name=yaml::$YAML"
      - run: cat rating-yaml.txt > .github/workflows/rating-chart.yml
      - id: changed
        run: git diff --exit-code
        continue-on-error: true
        name: Commit changes
      - if: ${{ steps.changed.outcome == 'failure' }}
        run: |
          git add README.md .github/workflows/rating-chart.yml
          git config --local user.name "Aditya Pal"
          git config --local user.email aditya.pal.science@gmail.com
          git commit --message 'Auto updating my readme and workflow!'
          git push -u origin master

